### ISSUE TITLE
can not build libcontainer

### ISSUE THREAD

**Issue by huikang** [docker/libcontainer#461] opened 2015-03-20 14:40 UTC
Hi, 
I build libcontainer from docker v1.5 and got this error. However, I used the same process from docker v.15 and succeed.

FATA[0001] Error response from daemon: Cannot start container d006de22ec002773068d282bab89f09e1af8e4b1e907b747bea2d162ee68426f: exec format error

Can anyone help? Thanks

The docker info output is
Containers: 12
Images: 226
Storage Driver: devicemapper
 Pool Name: docker-8:1-268200-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 6.638 GB

Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.18.8-criu
Operating System: Ubuntu 14.04.2 LTS

**Comment by LK4D4** [comment] 2015-03-20 15:35
@huikang Can you describe your steps?

**Comment by avagin** [comment] 2015-03-24 13:17
I saw the same error and it was fixed by https://github.com/docker/libcontainer/commit/69228248334a576549a9af9df389b3cbfe0c211c .

**Comment by mrunalp** [comment] 2015-03-31 22:59
Closing as the issue is fixed.

**Closed by mrunalp** 2015-03-31 22:59 UTC
